### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by moore3071** [OSUOSC/office#2]
In an effort to make source all OSC projects are as open as possible, we'd like to add a license to this project. The three contributors can debate it out as to which license is used.

- [x] @notori0us 
- [x] @meinwald 
- [x] @bsilvereagle

**Comment by bsilvereagle** [comment]
MIT works with me if we're trying to be consistent with the license we use as a club. 

I'm also open to Apache or GPL.

**Comment by bsilvereagle** [comment]
It looks like @meinwald code is CC0, I'm okay with all my code/hardware assets being CC0 as well.

**Comment by meinwald** [comment]
Sorry, responded to the wrong issue previously as I had not
realized there were two including me. Consider "deprecated"
directory CC0, i.e. feel free to relicense it or a combined
work with whatever you feel is appropriate. The original
script I made didn't really do much of anything.

**Comment by notori0us** [comment]
I approve with any changes before this comment
